name:                high-command
version:             0.1.0.0
github:              "AugmenTab/high-command"
license:             BSD3
author:              "Tyler Baum"
maintainer:          "tyler.baum@protonmail.com"
copyright:           "2023 Tyler Baum"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AugmenTab/high-command#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- extra
- flipstone-prelude
- gi-gtk
- gi-gtk-hs
- Hclip
- haskell-gi-base
- random
- text

default-extensions:
  - DeriveDataTypeable
  - DerivingStrategies
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings

ghc-options:
- -j
- -Werror
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wmissing-deriving-strategies
- -Wmissing-export-lists
- -fno-warn-orphans

library:
  source-dirs: src

executables:
  high-command-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - high-command
